version: '3.9'

services:
  fastapi-app:
    image: docker-fastapi:latest
    build:
      context: .
      dockerfile: deploy/python/Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - fastapi-db
    environment:
      DB_HOSTNAME: 0.0.0.0:5432/fastapi-db
      DB_PASSWORD: 123
    volumes:
      - static:/app/static

  fastapi-db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: fastapi-db
      POSTGRES_PASSWORD: 123

volumes:
  static: